name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-inclusive-naming-check:
    name: Inclusive Naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@7aa0f7a606f182bd03a7adb28e0d710216101ca5 # main
    with:
      fail-on-error: "true"

  lint-unit:
    name: Lint Unit
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@6ee58c37d404effad4598ce7b523dbaf0cb99285 # main
    with:
      with-uv: true
      python: "['3.10', '3.12']"
    needs:
      - call-inclusive-naming-check

  charmcraft-channel:
    runs-on: ubuntu-24.04
    outputs:
      channel: ${{ steps.charmcraft.outputs.channel }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - id: charmcraft
        run: echo "channel=$(cat .charmcraft-channel)" >> $GITHUB_OUTPUT

  charmcraft-build:
    name: Build Charm
    needs: [charmcraft-channel]
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Install and prepare LXD snap environment
        run: |
          sudo apt-get remove -qy lxd | true
          sudo snap list lxd | true
          sudo snap install lxd --channel=latest/stable
          sudo snap refresh lxd --channel=latest/stable
          sudo lxd waitready
          sudo lxd init --auto
          sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
          sudo lxc network set lxdbr0 ipv6.address none
          sudo usermod -a -G lxd $USER
          sg lxd -c 'lxc version'
      - name: Remove Docker
        run: |
          sudo rm -rf /etc/docker
          sudo apt-get purge moby-buildx moby-engine moby-cli moby-compose moby-containerd moby-runc -y
          sudo iptables -P FORWARD ACCEPT
      - name: Install Charmcraft
        run: |
          sudo snap install charmcraft --classic --channel=${{ needs.charmcraft-channel.outputs.channel }}
      - name: Build Charm
        run: |
          sg lxd -c 'charmcraft pack -v'
      - name: Upload charm artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: gcp-k8s-storage.charm
          path: ./gcp-k8s-storage*.charm
      - name: Upload debug artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: charmcraft-logs
          path: /home/runner/snap/charmcraft/common/cache/charmcraft/log/charmcraft-*.log
